### ISSUE TITLE
有关动态加载代码

### ISSUE THREAD

**Issue by aeoogo** [xueliangGit/koa-dir-router#2]
这种动态加载代码的功能再debug的时候太亟需了，我想将swagger的route也改成这种加载方式，您能为我提供些思路吗？

**Comment by xueliangGit** [comment]
看这里，这个程序的流程图： https://github.com/xueliangGit/koa-dir-router/blob/master/koa-dir-router.png

**Comment by aeoogo** [comment]
太棒了，感谢百忙中画出流程图。
